# Note 
#   [1] The volume should be owned by the user/group with the UID/GID specified in the config file. 
#       If you don’t give the volume correct permissions, the container may not start.
#   [2] Disabled registration, after which only admin can create accounts for users.
#   [3] Initializate localadmin / Localadmin@Rdisw2fun
version: "2"

networks:
  gitea:
    external: false

services:
  gitea-server:
    image: gitea/gitea:1
    environment:
      - USER_UID=502
      - USER_GID=20
      - DB_TYPE=mysql
      - DB_HOST=gitea-db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - DISABLE_REGISTRATION=true
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
       - "53000:3000"
       - "53022:22"
    depends_on:
      - gitea-db

  gitea-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
    